apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-finance
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: syedumairanwar/banking-finance
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bankingwebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
